export const homeroomStudents = [
  {
    id: 'hr-anna',
    name: 'Anna Nguyen',
    email: 'anna.nguyen@example.com',
    phone: '0901234567',
    address: 'District 1, Ho Chi Minh City',
    dateOfBirth: '2008-05-12',
    gender: 'Female',
    level: 'IELTS',
    parentName: 'Nguyen Van A',
    parentPhone: '0911111111',
    enrolledDate: '2025-09-03',
    note: 'Needs extra support on writing cohesion.',
    avatarColor: 'bg-violet-500',
    overallStatus: 'in_review',
    assignments: [
      { id: 'a1', title: 'Reading Homework - Week 3', status: 'Submitted', gradingStatus: 'Pending' },
      { id: 'a2', title: 'Listening Module 5', status: 'Submitted', gradingStatus: 'Done' },
      { id: 'a3', title: 'Writing Task 2 Practice', status: 'Missing', gradingStatus: 'Pending' },
    ],
  },
  {
    id: 'hr-bao',
    name: 'Bao Tran',
    email: 'bao.tran@example.com',
    phone: '0902345678',
    address: 'Thu Duc City, Ho Chi Minh City',
    dateOfBirth: '2008-03-20',
    gender: 'Male',
    level: 'ACA',
    parentName: 'Tran Thi B',
    parentPhone: '0922222222',
    enrolledDate: '2025-08-20',
    note: '',
    avatarColor: 'bg-blue-500',
    overallStatus: 'on_track',
    assignments: [
      { id: 'a1', title: 'Reading Homework - Week 3', status: 'Submitted', gradingStatus: 'Done' },
      { id: 'a2', title: 'Listening Module 5', status: 'Submitted', gradingStatus: 'Done' },
      { id: 'a3', title: 'Speaking Shadowing', status: 'Submitted', gradingStatus: 'Pending' },
    ],
  },
  {
    id: 'hr-chi',
    name: 'Chi Le',
    email: 'chi.le@example.com',
    phone: '0903456789',
    address: 'District 7, Ho Chi Minh City',
    dateOfBirth: '2007-11-01',
    gender: 'Female',
    level: 'IELTS',
    parentName: 'Le Van C',
    parentPhone: '0933333333',
    enrolledDate: '2025-09-10',
    note: 'Frequently late on Monday assignments.',
    avatarColor: 'bg-rose-500',
    overallStatus: 'needs_attention',
    assignments: [
      { id: 'a1', title: 'Reading Homework - Week 3', status: 'Missing', gradingStatus: 'Pending' },
      { id: 'a2', title: 'Listening Module 5', status: 'Submitted', gradingStatus: 'Done' },
      { id: 'a3', title: 'Writing Task 2 Practice', status: 'Missing', gradingStatus: 'Pending' },
    ],
  },
  {
    id: 'hr-duy',
    name: 'Duy Pham',
    email: 'duy.pham@example.com',
    phone: '0904567890',
    address: 'Binh Thanh District, Ho Chi Minh City',
    dateOfBirth: '2008-09-14',
    gender: 'Male',
    level: 'IELTS',
    parentName: 'Pham Thi D',
    parentPhone: '0944444444',
    enrolledDate: '2025-09-01',
    note: '',
    avatarColor: 'bg-emerald-500',
    overallStatus: 'on_track',
    assignments: [
      { id: 'a1', title: 'Reading Homework - Week 3', status: 'Submitted', gradingStatus: 'Done' },
      { id: 'a2', title: 'Listening Module 5', status: 'Submitted', gradingStatus: 'Done' },
      { id: 'a3', title: 'Writing Task 2 Practice', status: 'Submitted', gradingStatus: 'Pending' },
    ],
  },
  {
    id: 'hr-hoa',
    name: 'Hoa Vu',
    email: 'hoa.vu@example.com',
    phone: '0905678901',
    address: 'Go Vap District, Ho Chi Minh City',
    dateOfBirth: '2008-01-18',
    gender: 'Female',
    level: 'ACA',
    parentName: 'Vu Van E',
    parentPhone: '0955555555',
    enrolledDate: '2025-08-27',
    note: 'Strong participation in class discussion.',
    avatarColor: 'bg-fuchsia-500',
    overallStatus: 'in_review',
    assignments: [
      { id: 'a1', title: 'Reading Homework - Week 3', status: 'Submitted', gradingStatus: 'Pending' },
      { id: 'a2', title: 'Listening Module 5', status: 'Missing', gradingStatus: 'Pending' },
      { id: 'a3', title: 'Vocabulary Sprint', status: 'Submitted', gradingStatus: 'Done' },
    ],
  },
  {
    id: 'hr-khanh',
    name: 'Khanh Do',
    email: 'khanh.do@example.com',
    phone: '0906789012',
    address: 'District 10, Ho Chi Minh City',
    dateOfBirth: '2007-12-25',
    gender: 'Male',
    level: 'IELTS',
    parentName: 'Do Thi F',
    parentPhone: '0966666666',
    enrolledDate: '2025-09-11',
    note: '',
    avatarColor: 'bg-indigo-500',
    overallStatus: 'in_review',
    assignments: [
      { id: 'a1', title: 'Reading Homework - Week 3', status: 'Submitted', gradingStatus: 'Pending' },
      { id: 'a2', title: 'Listening Module 5', status: 'Submitted', gradingStatus: 'Pending' },
      { id: 'a3', title: 'Writing Task 2 Practice', status: 'Submitted', gradingStatus: 'Pending' },
    ],
  },
  {
    id: 'hr-linh',
    name: 'Linh Hoang',
    email: 'linh.hoang@example.com',
    phone: '0907890123',
    address: 'District 3, Ho Chi Minh City',
    dateOfBirth: '2008-06-08',
    gender: 'Female',
    level: 'ACA',
    parentName: 'Hoang Van G',
    parentPhone: '0977777777',
    enrolledDate: '2025-08-30',
    note: '',
    avatarColor: 'bg-teal-500',
    overallStatus: 'needs_attention',
    assignments: [
      { id: 'a1', title: 'Reading Homework - Week 3', status: 'Missing', gradingStatus: 'Pending' },
      { id: 'a2', title: 'Listening Module 5', status: 'Submitted', gradingStatus: 'Done' },
      { id: 'a3', title: 'Speaking Shadowing', status: 'Missing', gradingStatus: 'Pending' },
    ],
  },
  {
    id: 'hr-minh',
    name: 'Minh Bui',
    email: 'minh.bui@example.com',
    phone: '0908901234',
    address: 'Tan Binh District, Ho Chi Minh City',
    dateOfBirth: '2008-02-02',
    gender: 'Male',
    level: 'IELTS',
    parentName: 'Bui Thi H',
    parentPhone: '0988888888',
    enrolledDate: '2025-08-18',
    note: 'Can improve consistency for weekly deadlines.',
    avatarColor: 'bg-amber-500',
    overallStatus: 'in_review',
    assignments: [
      { id: 'a1', title: 'Reading Homework - Week 3', status: 'Submitted', gradingStatus: 'Pending' },
      { id: 'a2', title: 'Listening Module 5', status: 'Submitted', gradingStatus: 'Done' },
      { id: 'a3', title: 'Writing Task 2 Practice', status: 'Submitted', gradingStatus: 'Pending' },
    ],
  },
];

