export const EXAM_DRAFT_VERSION = 2;
export const EXAM_DRAFT_TTL_MS = 24 * 60 * 60 * 1000;
export const LISTENING_AUDIO_REWIND_SECONDS = 5;
export const LISTENING_TIMER_REWIND_SECONDS = 10;
export const LISTENING_RESUME_NOTICE_MS = 3800;
export const MOBILE_READING_DRAWER_MAX_WIDTH = 860;
export const TRACKING_HEARTBEAT_MS = 30 * 1000;
export const TRACKING_ANSWER_DEBOUNCE_MS = 700;
